@startuml component
skinparam linetype ortho 
' skinparam linetype polyline 
skinparam roundcorner 15

together {
      actor User as user
      actor Curator as curator
      actor EventOwner as eventowner
}

together {
      component [frontend-web-user] as frontendwebuser  
      component [frontend-web-curator] as frontendwebcurator
      component [frontend-web-event] as frontendwebevent
}


together {
      together {
      component [service-playlist-api] as serviceplaylistapi  
      component [service-playlist-db] as serviceplaylistdb

      }
      component [service-user] as serviceuserapi
      component [service-event] as serviceeventapi  
      component [service-playback-ctrl] as serviceplaybackctrl
}

together {
      component [boundary-spotify] as boundaryspotify  
}

cloud  {
  component SpotifyAPI  as spotifyapi
}


user -down-> frontendwebuser
curator -down-> frontendwebcurator
eventowner -down-> frontendwebevent

frontendwebuser -down-> serviceuserapi
frontendwebuser -down-> serviceeventapi
frontendwebuser -down-> serviceplaylistapi
serviceplaylistapi -down-> serviceplaylistdb

serviceplaybackctrl -right-> serviceplaylistapi
serviceplaybackctrl --> boundaryspotify

boundaryspotify --> spotifyapi 
@enduml
