@startuml component
skinparam linetype ortho 
' skinparam linetype polyline 
skinparam roundcorner 15

together {
      actor User as user
      actor Curator as curator
      actor EventOwner as eventowner
}

component [frontend-web] as frontendweb 

component [service-bffweb] as servicebffweb 

together {
      component [service-playlist] as serviceplaylist 
      component [service-user*] as serviceuser
      component [service-event*] as serviceevent
}

together {
      component [provider-spotify] as backendspotify  
      component [provider-soundcloud*] as backendsoundcloud  
}
together {
      component [backend-eventstore] as backendeventstore
      component [backend-db*] as backenddb
}

cloud  {
  component SpotifyAPI  as spotifyapi
}


user -down-> frontendweb
curator -down-> frontendweb
eventowner -down-> frontendweb

frontendweb -down-> servicebffweb

servicebffweb -down-> serviceuser
servicebffweb -down-> serviceevent
servicebffweb -down-> serviceplaylist
servicebffweb -down-> backendeventstore


serviceplaylist -down-> backendspotify
serviceplaylist -down-> backendsoundcloud
serviceplaylist -down-> backendeventstore
serviceuser -down-> backenddb

backendspotify -down-> backendeventstore
backendsoundcloud -down-> backendeventstore

backendspotify -down--> spotifyapi 

note bottom of serviceevent: Components marked with * are not part of MVP

@enduml
