@startuml component
'skinparam monochrome true
'skinparam handwritten true


together {
  actor User
  actor Curator
  actor EventOwner
}

cloud  {
node OpenDJ as System
' TODO: Do we want to embedd / show components here already?
'{
' component frontend 
' component playlist 
' component spotify 
' }
}

User -> System
Curator -> System
EventOwner -> System

cloud  {
  component SpotifyAPI 
  component GoogleAuthAPI 
}

entity PlaybackDevice

'User ^-- Curator
'User ^-- EventOwner


System ..> SpotifyAPI
System ..> GoogleAuthAPI
SpotifyAPI -> PlaybackDevice
@enduml
